version: "~> 1.0"

gobuild_args: -v --tags apitests

env:
  - ZITI_TEST_LOG_LEVEL=fatal

before_script:
  - go vet ./...

script:
  - go test -v -timeout 8m ./... --tags apitests

#script:
#  - set -e
#  - mkdir test-output
#  - go test -v ./... --tags apitests > test-output/tests.log

# after_failure:
#  - set -e
#  - pip install --upgrade --user pip
#  - pip install awscli
#  - aws s3 sync test-output s3://ziti-ci/$TRAVIS_BUILD_ID

import:
  - source: netfoundry/ziti-ci:ziti-go-defaults.yml@v1
